### ISSUE TITLE
issues with tower.app (was: Plugins not working)

### ISSUE THREAD

**Issue by aranw** [mroth/lolcommits#83]
I added the following to my `config.yml` file.

```
--- 
tranzlate: 
  enabled: true
loltext: 
  enabled: true
```

And it seems the image isn't getting the translated commit message added, I don't know whether my images should be renamed as well but I only ever have the one image, `tmp_snapshot.jpg`
